labels.npy corrisponde alla struttura che contiene le info di classe, oggetto e posizione sulla griglia. Nel caso del codice che ho su github, 

 0 = row_id, 1 = col_id, 2 = class_id, colonna 3 = object_id

In [4]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 10.7 MB 112 kB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/hs/_bfkhw2j1s7f41ggmr2j70p80000gp/T/tmpkqkqy8wv
       cwd: /private/var/folders/hs/_bfkhw2j1s7f41ggmr2j70p80000gp/T/pip-install-bgez1lof/numpy
  Complete output (1342 lines):
  Running from numpy source directory.
  setup.py:86: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python 

In [29]:
import numpy as np
data = np.load('SITS-Missing-Data/D1_balaruc_samples.npy')
masks = np.load('SITS-Missing-Data/D2_balaruc_masks.npy')
lut = np.load('SITS-Missing-Data/D3_balaruc_lut.npy')

In [7]:
data.shape, masks.shape, lut.shape

((137606, 54, 16), (137606, 54), (137606, 4))

In [35]:
data[np.where(masks == 1)] = MISSING_VALUE
num_steps = data.shape[1]
num_bands = data.shape[2]
labels, num_classes = transfer_labels(lut[:, 1])
labels = convertToOneHot(labels, num_classes=len(np.unique(labels)))
prediction_target = data[:, 1:]
mask = np.ones_like(prediction_target)
mask[np.where(prediction_target == MISSING_VALUE)] = 0

In [60]:
np.where(data == MISSING_VALUE)



(array([     0,      0,      0, ..., 137605, 137605, 137605]),
 array([ 1,  1,  1, ..., 51, 51, 51]),
 array([ 0,  1,  2, ..., 13, 14, 15]))

In [9]:
data[0][0]

array([0.02333209, 0.03176535, 0.0506984 , 0.08257182, 0.09480418,
       0.08718403, 0.07081016, 0.10434756, 0.1462604 , 0.11773191,
       0.5620112 , 0.34162304, 0.10032066, 0.21352541, 0.65649986,
       0.45288923], dtype=float32)

In [13]:
masks[0]

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0], dtype=uint8)

In [23]:
prediction_target = data[:, 1:]
masks = masks[:, 1:]
mask = np.ones_like(prediction_target)
mask[np.where(masks == 1)] = 0

In [28]:
mask[0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [17]:
from utils import *

In [19]:
data = np.load('SITS-Missing-Data/D1_balaruc_samples.npy')
masks = np.load('SITS-Missing-Data/D2_balaruc_masks.npy')
lut = np.load('SITS-Missing-Data/D3_balaruc_lut.npy')
check_missing_ratio(masks)
num_steps = data.shape[1]
num_bands = data.shape[2]
labels, num_classes = transfer_labels(lut[:, 1])
labels = convertToOneHot(labels, num_classes=len(np.unique(labels)))

MISSING RATIO: 0.6670418656378572


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [ ]:
np.where(a == 1)
a.shape, np.count_nonzero(a)
#np.count_nonzero(a)
masks.shape
#np.count_nonzero(masks, keepdims=True)

(137606, 54)

In [ ]:
lut.shape
# 0: IdObject, 1: Class, 2: ?, 3: ?

(137606, 4)

In [ ]:
clID_col = lut[:, 1]
clID = np.unique(clID_col)
hashClID2obj = {}
for val in clID:
        idx = np.where(clID_col == val)
        t_labels = lut[idx]
        hashClID2obj[val] = np.unique( t_labels[:,0] )

In [ ]:
hashClID2obj.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
hashClID2obj[1]

array([ 711,  712,  713,  714,  715,  716,  717,  718,  719,  720,  721,
        722,  723,  724,  725,  726,  727,  728,  729,  730,  731,  732,
        733,  734,  735,  736,  737,  738,  739,  740,  741,  742,  743,
        744,  745,  746,  747,  748,  749,  750,  751,  752,  753,  754,
        755,  756,  757,  758,  759,  760,  761,  762,  763,  764,  765,
        766,  767,  768,  769,  770,  771,  772,  773,  774,  775,  776,
        777,  778,  779,  780,  781,  782,  783,  784,  785,  786,  787,
        788,  789,  790,  791,  792,  793,  794,  795,  796,  797,  798,
        799,  800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
        810,  811,  812,  813,  814,  815,  816,  817,  818,  819,  820,
        821,  822,  823,  824,  825,  826,  827,  828,  829,  830,  831,
        832,  833,  834,  835,  836,  837,  838,  839,  840,  841,  842,
        843,  844,  845,  846,  847,  848,  849,  850,  851,  852,  853,
        854,  855,  856,  857,  858,  859,  860,  8

In [ ]:
import utils

2022-03-01 18:09:30.166785: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-01 18:09:30.166822: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [ ]:
training, validation, test, num_classes, num_steps, num_bands = utils.load_sits()

In [ ]:
training.cardinality(), validation.cardinality(), test.cardinality()

(<tf.Tensor: shape=(), dtype=int64, numpy=59764>,
 <tf.Tensor: shape=(), dtype=int64, numpy=49175>,
 <tf.Tensor: shape=(), dtype=int64, numpy=28667>)

In [ ]:
training.cardinality(), validation.cardinality(), test.cardinality()

(<tf.Tensor: shape=(), dtype=int64, numpy=56336>,
 <tf.Tensor: shape=(), dtype=int64, numpy=32095>,
 <tf.Tensor: shape=(), dtype=int64, numpy=49175>)